[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rapidsim"
version = "1.0.8"
description = "A Python wrapper for RAPID code"
readme = "README.md"
authors = [
    { name = "Dóra Tarczay-Nehéz" }
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
]
dependencies = [
    "PyYAML", 
]

[project.scripts]
rapidsim = "rapidsim.wrapper:main"

[tool.setuptools]
packages = ["rapidsim"]
include-package-data = true